
["flash shield"]
	#max durability of flash shield
	#Range: 1 ~ 32767
	flash_shield_max_durability = 450
	#cooldown of flash shield in ticks
	#Range: 20 ~ 32767
	flash_shield_cooldown = 200

[throwable]
	#modifier of initial speed when crouching, 1.0 means no change
	#Range: 0.01 ~ 2.0
	flash_shield_cooldown = 0.5

[melee]
	#maximum number of targets can contains in melee attack request packet
	#Range: 1 ~ 512
	melee_max_target = 32

